### ISSUE TITLE
Results table

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#17]
Looking like raw markup at the moment.

**Comment by Wilto** [comment]
Reassigned.

**Comment by yoavweiss** [comment]
Just one comment - the current result table is just the summary. We'll also
need the "drill-down" per URL table at some point

**Comment by Wilto** [comment]
Ah yes. We’re probably fine to just do these as wide-open `table` styles, site being as small as it is.
