### ISSUE TITLE
We need a design, for starters.

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#2]
I think we also need a theme song, but maybe that’s just me.

@starburst1977, can you work with @hellogeri on framing this thing out? We’ve been discussing this being a two-pager:

The first page being a quick description of what the site is all about, and an input that accepts a URL.

The second page (which will either be shown on submission of the URL or via an emailed link, depending on how the back-end delay plays out), will contain the results—and likely a URL input for additional testing. I’ve asked @nwtn to share some sample data so we can start blocking that out.

Thanks, guys!

**Comment by nwtn** [comment]
yahoo.com, which isn't responsive:

```
url               viewport          image_data        optimize_savings  resize_savings
http://yahoo.com  360               135942            0                 4295
http://yahoo.com  720               124172            0                 2214
http://yahoo.com  1260              140840            0                 4141
```

ebay.com, not responsive:

```
url              viewport          image_data        optimize_savings  resize_savings
http://ebay.com  360               749566            0                 330322
http://ebay.com  720               721940            0                 330322
http://ebay.com  1260              749695            0                 330322
```

starbucks.com, responsive:

```
url                   viewport          image_data        optimize_savings  resize_savings
http://starbucks.com  360               370334            0                 66342
http://starbucks.com  720               370334            0                 68587
http://starbucks.com  1260              370334            0                 70222
```

these all happen to have their images properly optimized. sorry. happy to post data from other URLs if you need.

btw, it takes a couple minutes to run, so you may want to think about what the user will be seeing while that happens. fancy spinners!

**Comment by Wilto** [comment]
Nice. Couple notes on the result data:
- All those values are in bytes, but we can math ’em over to kilobytes on the back-end, so let’s plan for that instead—easier to read, I figure.
- We won’t need to repeat the URL in the results table.
- The list of viewports to test is customizable, so we’ll need a way to represent those options on the front-end. Maybe something to the tune of:

![bp-list](https://f.cloud.github.com/assets/439942/1124382/be4b68b8-1afd-11e3-914a-bd6b5c4b0895.png)

**Comment by Wilto** [comment]
( Don’t sweat the interaction details on that wireframe; I just built one of these editable list dealies not too long ago, so I can rework it for this. )

**Comment by starburst1977** [comment]
Ok. Anything existing that needs to be respected? Overarching designs, logos, styleguides, etc.?

**Comment by Wilto** [comment]
There are some RICG design assets at http://responsiveimages.org/RICG-Logos.zip along with some display guidelines, and http://responsiveimages.org is the general vibe. If you need any sources for assets already in play, either @hellogeri or I should have them kicking around somewhere.

@yoavweiss, you cool with this falling under the RICG branding?

**Comment by philiprenich** [comment]
I'd be willing to jump in as much as I can as well.

**Comment by yoavweiss** [comment]
100% cool with RICG branding.

**Comment by starburst1977** [comment]
Awesome, thanks. Will start working on it the evening.

**Comment by starburst1977** [comment]
Btw: Any specific browser that it needs to work in (besides modern chrome/Firefox/IE)? Just checking before I go wild and notice afterwards it should work in IE6 :)...

**Comment by Wilto** [comment]
@starburst1977:
We’re pretty crazy about progressive enhancement around these parts (okay, I am pretty crazy about progressive enhancement). Since this basically boils down to a couple of forms and a table: I’m betting we can cover a ton of ground on this support-wise, though the levels of “enhancement” might differ. I’d probably qualify the enhanced scripts and styles on `querySelectorAll` support, but we can wing it. Let’s start with a comp or a prototype—however you’re more comfortable designing—then I can set this sucker up with a Filament-Group-style PE foundation and we can run with it from there.

**Comment by hellogeri** [comment]
@starburst1977 Looking forward to seeing it! If you need any design elements or anything else specific, just let me know!

**Comment by Wilto** [comment]
@starburst1977: Feel free to chuck any work-in-progress into the thread here, yeah?

**Comment by starburst1977** [comment]
@Wilto I will do today. Getting there slowly.

**Comment by Wilto** [comment]
No worries, man! We’re excited to see it.

**Comment by starburst1977** [comment]
First preview & still work in progress: http://www.strbr.st/ricg/. This is the direction I liked the most so far. 

Some real life text would be good, to get the real feel. And I need to make better icons & a decent footer. At the moment, I would recommend using Chrome for viewing (due to haven't looked at it in any other browser yet :)...).

**Comment by Wilto** [comment]
Looking good!

@hellogeri can speak to this better than I can, but I might finesse the colors a bit in the final product for the sake of upping the contrast—I dig the backgrounds pulled from the logo, though.

**Comment by starburst1977** [comment]
Yes, you might be right that I should soften out the background colors a bit. Will give it a try.

**Comment by hellogeri** [comment]
Just had another peek, and it seems like the contrast has been bumped up, which is great! Thanks for doing that! 

I'll wait until you have more done with the footer and whatever before giving more feedback. Just let us know when you're ready for me to check.

**Comment by Wilto** [comment]
Not to jump in preemptively, but maybe it would make sense to swap the contents of the second and third “tiers?” It would keep the tool itself front-and-center, not that I’m any sort of believer in “the fold”—but mainly, it would mean the smaller copy would be against the lighter background, whereas the text for the tool itself is mostly larger headings that would still be readable on the slightly darker background.

**Comment by starburst1977** [comment]
Now the responsive stuff works too: http://www.strbr.st/ricg/. How about some content for me to fill in?

**Comment by jefflembeck** [comment]
@Wilto @yoavweiss We still need something to fill in the Lorem Ipsum left in there.

**Comment by Wilto** [comment]
We got us a design. Great work, @starburst1977.

Closing this and filing a few fit-and-finish issues for myself.

**Comment by starburst1977** [comment]
Your welcome. Didn't have time so far to build the results page. No need for that anymore?

**Comment by Wilto** [comment]
@starburst1977 Figure the plan is to either drop the copy “block” in favor of the results table, or add the table to it—I’m leaning towards the latter. The prototype is semi-live (don’t pass this link around) at http://sizersoze.org, if you want to have a look at the current behavior. Let me know what you’re thinking.

**Comment by starburst1977** [comment]
@Wilto Looks quite nice actually. The shark-cat really kicks ass :). But I would recommend a button to start the procedure ("Start testing" or something) and I could take care of the results table.

**Comment by Wilto** [comment]
@starburst1977: Good call.
