### ISSUE TITLE
`px` hard-coded in selects; no other options available

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#22]
I haven’t dug through to see if anything is actually checking those `selects`, but we should get `em` working in there as well.

**Comment by anselmh** [comment]
It isn't evaluated right now and to be honest, how do you want to evaluate `em`? Assuming a base font-size of 16px? We could then add a function to calculate the px result out of the given em value…

**Comment by Wilto** [comment]
Yeah, just based on 16px, and we’d do a little math behind the scenes. Just a convenience thing on the front-end.

**Comment by anselmh** [comment]
Okay, we should do that. Maybe I can come up with something tomorrow…

**Comment by Wilto** [comment]
That’d be awesome, man. Thanks!

**Comment by anselmh** [comment]
It's in now: https://github.com/ResponsiveImagesCG/Sizer-Soze-frontend/commit/e94dc0f8de47551075698e3d159515a0555df99b
