### ISSUE TITLE
We gotta make this thing work, also

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#3]
I know @jlembeck had a look-see at wiring up the server side of the equation, but I’m not certain where that left off. If I recall correctly, the latest version of the script is Python instead of Bash, which meant Complications™?

@jlembeck:
If you have a minute or two free, you mind writing up the current score on this?

**Comment by jefflembeck** [comment]
My problem came in the: "Not sure how to wire up the python version of this" area. I started a node version and can finish rewriting that if that's what everybody is more comfortable with.

@yoavweiss and I had discussed this earlier and he worried about the problems with Node being single-threaded, but I think we can address that issue pretty easily by making some of the parts of this run as forked processes.

If it's preferable that we move along with it via python, it'd probably be best to get somebody who knows python well enough to at least put together the beginning setup of some sort of framework (Flask?/Django?) for us to work within the confines of.

**Comment by yoavweiss** [comment]
@jlembeck I'm cool with rewriting the thing in Node. I have expressed fear of the lack of Node multi-threading. That was before I found out that Python's multi-threading is pretty useless in practice, and if you want to parallelize CPU work, it needs to be done by forking new processes.

So, if you're taking it up on yourself to rewrite the backend in Node, I'm there to learn and assist :)

**Comment by yoavweiss** [comment]
Alternatively, I can also wire up the Django parts.

**Comment by jefflembeck** [comment]
I don't have too many opinions on which tech to use beyond a "I know this thing pretty well." I can definitely get some stuff done in JS quite a bit faster and assume that others who are interested in helping on this project likely help out a little faster if they need to write something in JS.

That being said, I'm at the mercy of people who make real decisions and wouldn't be able to get this on my plate for about a week anyway, so if there is a push to get this started ASAP, my opinions don't matter too much anyway :)

**Comment by Wilto** [comment]
For anyone tuning in late, the project is https://github.com/yoavweiss/sizer-soze — we’re building a web-based version, for the sake of anyone that can’t/won’t muck around with running this on the command line. It’s in Python now, which we could use on the back-end as well, but I’m definitely no expert there. @jlembeck started working on a Node version, as well.

Here’s how that might play out visually: http://www.strbr.st/ricg/

**Comment by Wilto** [comment]
@garann and @jlembeck are gonna join forces on this sucker next week.

**Comment by yoavweiss** [comment]
Very initial (& fragile) version is available on http://sizersoze.org

**Comment by nwtn** [comment]
Fragile as in the data it's spitting out can't be trusted, or fragile as in it might die?

**Comment by yoavweiss** [comment]
Might die

**Comment by jefflembeck** [comment]
@yoavweiss which end is the weak end right now? I can look at FE bugs if there are any. Just create and assign em.

**Comment by Wilto** [comment]
BOOM. Calling this “working” and closing the issue. Gonna file a seperate issue for “may not always be ‘working’ in the strictest sense.”
