### ISSUE TITLE
Results table overflowing container/page

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#34]
![image](https://cloud.githubusercontent.com/assets/439942/2770000/f693bbf2-ca58-11e3-8aa1-0f298b844125.png)

TODO: offer @zachleat one (1) American dollar in exchange for adding a Top Secret Filament Group Project.

**Comment by Wilto** [comment]
_Nice_. Thanks, man.

**Comment by zachleat** [comment]
Happy to help! (late comment)
