### ISSUE TITLE
remove() doesn't work in IE

### ISSUE THREAD

**Issue by gregwhitworth** [ResponsiveImagesCG/Sizer-Soze-frontend#38]
Hey everyone, great site! I was testing this out in IE and remove() isn't supported from the DOM4 spec, but that is what is currently being used to remove the breakpoints, so you get an exception and that kills the script. I suggest adding the remove() method to the prototype chain so that it works across all browsers. 

Here is a reduction of the issue: http://jsfiddle.net/SvDVn/5/

Thanks!

**Comment by Wilto** [comment]
Thanks!
