### ISSUE TITLE
The Delay

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/Sizer-Soze-frontend#4]
The script has a thirty second delay for the sake of async-loaded images. I figure there are three ways we can go with this:

_Show results immediately after form submission:_
1) Remove the delay, and maybe disclaim that the web-based tool only covers images loaded with the initial markup.
2) Reduce the delay, and add an interstitial “please hold…” page. I’d think a handful of seconds would mostly cover us here, yeah?

_Email a link to a results page:_
3) Leave it the way it is.

The email-for-results method feels kinda clunky to me, and I’m not sure the difference would outweigh the clunkiness.

Wat’chu think, @yoavweiss?

**Comment by nwtn** [comment]
My preference from a user perspective would be (2), especially if the interstitial was adorable.

**Comment by Wilto** [comment]
I’m leaning that way myself.

**Comment by yoavweiss** [comment]
I plan on enabling several options on the backend: custom delay, ignoring
these images altogether, etc.
Once I'd do that, I want to see how much of the image data we're talking
about comes from display:none.
If it's negligible, we can safely ignore that.
If it's large part of the savings, we shouldn't ignore it.

So... data

**Comment by jefflembeck** [comment]
A post-back wouldn't be a terrible idea. So, 2.

**Comment by starburst1977** [comment]
I would prefer going for the second option, too. Getting the results via an email causes an disruption that would be difficult to communicate to the user. On the other side: A short delay would indicate that difficult stuff is happening behind the scenes (which you would lose if you remove the delay completely). And getting the results would feel more important.

**Comment by jefflembeck** [comment]
Current status on this: there is a youtube video that plays while you wait.

**Comment by Wilto** [comment]
p sweet cat and duck imo

Closing.
