### ISSUE TITLE
Framework/Markup Choice

### ISSUE THREAD

**Issue by jefflembeck** [ResponsiveImagesCG/Sizer-Soze-frontend#5]
I'm partial to Express/EJS, as I'm pretty familiar to both. I'll defer to somebody who has written far more Node than I have: @garann, any new hotness to holla at/huge warnings on those?

Other tech choices can be talked in here as well: I assume Grunt for the build tool and nodeunit/qunit for tests?

**Comment by garann** [comment]
Yeah, I go with Express for most things, too. I kinda like something that's not just straight JS for the templates. I usually go with doT, but Handlebars or Mustache I like too. Not that it's a big deal, I just have opinions. :)

Grunt/nodeunit/qunit all seem fine to me!

**Comment by Wilto** [comment]
have we considered using html

am i helping

**Comment by garann** [comment]
Heyyyyyyy wat happens

Y'all came up at Fronteers and it reminded me of this project. Still working on it?

**Comment by jefflembeck** [comment]
Hey @garann,

I need a bit of help getting this off of the ground (have a lot less time than I was planning on having). I'll make some tickets describing what we need to do. :/

**Comment by jefflembeck** [comment]
No framework chosen. We have a static site up. Can revive this when the changes are needed.
