### ISSUE TITLE
Hosting solution

### ISSUE THREAD

**Issue by jefflembeck** [ResponsiveImagesCG/Sizer-Soze-frontend#8]
Anybody have anything that is Mad Decent™?

I like Digital Ocean. Pretty cheap and getting a deployment solution together relatively quickly is pretty easy. We can also likely just use Heroku for this.

**Comment by Wilto** [comment]
<img src="http://wil.to/_/mad-decent.gif">

**Comment by jefflembeck** [comment]
@yoavweiss has a solution for hosting. If I get a vm up and running with Vagrant, do you think you can use it for deployment @yoavweiss ?

**Comment by yoavweiss** [comment]
@jlembeck - Ideal for me would be to hook up the FE on the same machine as the service. It currently has an nginx running (serving python stuff using uwsgi). So I'd refer a script over a ready made VM.
How do we usually hook up node to nginx?

**Comment by jefflembeck** [comment]
Yoav is taking care of this. It's currently a static site.
