### ISSUE TITLE
Mock Responses from Sizer-Soze service

### ISSUE THREAD

**Issue by jefflembeck** [ResponsiveImagesCG/Sizer-Soze-frontend#9]
So.

A. We need to decide what information that Sizer Soze gives us is crucial to this site. 

B. Once we have that, we need to mock a few different URL requests so we can build the models around it. 

@garann - Do you have any experience with mocking responses for testing in Node?

**Comment by garann** [comment]
Hey hi. Yes! I just had to do that for another project, so it's all still fresh in my mind. Hit me with some requirements and I can whip something up.

**Comment by Wilto** [comment]
<img src="http://wil.to/_/bruce-willie.gif">

**Comment by jefflembeck** [comment]
Ok The request url is of the format:

```
http://api.sizersoze.org/api/?viewport=680,1260&target_url=blog.cloudfour.com&ignore_invisibles=0&postback_url=bla.bla.com
```

The postback url will receive data looking like this

```
 {"details": [["/tmp/sizer/http-google-com/5a/http-www-google-fr-images-icons-product-chrome-48-png", 1834, 0, -36, "48x48=>48x48", 0]], "summary": {"url": "http://google.com", "postback": "bla.com", "lossy": -36, "resize": 0, "viewport": "360", "image_data": 1834, "lossless": 0}}
```

**Comment by yoavweiss** [comment]
Service is up and running! \o/

**Comment by jefflembeck** [comment]
Ok, request URL is actually in this format

```
http://api.sizersoze.org/api/?viewports=680,1260&target_url=blog.cloudfour.com&ignore_invisibles=0&postback_url=bla.bla.com
```

Note: viewports instead of viewport

**Comment by jefflembeck** [comment]
I still need to write tests like nobody's business. Oof.

**Comment by Wilto** [comment]
Workin’; shippin’ it.
